name: CI-CD Pipeline (No Docker)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.HOST }}
        username: ec2-user
        key: ${{ secrets.SSH_KEY }}
        script: |
          # Install required tools (non-interactive)
          sudo dnf install -y git python3

          # Clone repo if not exists
          if [ ! -d "devops-02mini-project" ]; then
            git clone https://github.com/MANI-07-code/devops-02mini-project.git
          fi

          cd devops-02mini-project

          # Pull latest code
          git pull origin main

          # Install dependencies
          pip3 install -r requirements.txt

          # Stop old app if running
          pkill -f app.py || true

          # Run app in background
          nohup python3 app.py > output.log 2>&1 &
